CC=gcc
CFLAGS= -Wall 

all: cmndline environ getenv process

cmndline: cmndline.c
	$(CC) $(CFLAGS) $+ -o $@

environ: environ.c
	$(CC) $(CFLAGS) $+ -o $@

getenv: getenv.c
	$(CC) $(CFLAGS) $+ -o $@

process: process.c
	$(CC) $(CFLAGS) $+ -o $@
